version: '3.9'
services:
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: flask_app_image:1.0  # Nom et version de l'image
    container_name: flask_app
    ports:
      - "5002:5002"
    environment:
      - FLASK_ENV=development
    restart: always