 name: voting_app

 on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main
    workflow_dispatch:

 jobs:
    build:
      runs-on: ubuntu-24.04
      steps:
        - uses: actions/checkout@v2
        - name: first-bash
          run: bash ./test.sh

        - name : Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.10'

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip  # update pip 
            pip install -r requirements.txt   # Install dependencies belong  requirements.txt
        - name: create repo and downloads files in this repo
          run: |
             mkdir voting_app_repo
             cp -r repo_voting voting_app_repo
             ls -al voting_app_repo/repo_voting
        - name: Upload files as artifact
          uses: actions/upload-artifact@v3
          with:
           name: shared-files
           path: voting_app_repo

    test:
      runs-on: ubuntu-24.04
      needs: build # this code depends on job build
      steps:
        - name: Check out code
          uses: actions/checkout@v2

        - name: Set up Python
          uses: actions/setup-python@v2
          with:
           python-version: '3.10'

        - name: install dependencies
          run: |
            python -m pip install --upgrade pip  # update pip 
            pip install -r requirements.txt   # Install dependencies belong  requirements.txt
        - name : copy code src
          run: |
            cp -r repo_voting ./my_repo
        - name : run test with pytest
          run: |
             pytest 
     

    sshconnection:
           runs-on: ubuntu-24.04
           steps:
               - name: Check out code
                 uses: actions/checkout@v2
               
               - name: install ssh keys
                 run: |
                   mkdir -p ~/.ssh
                   
                   echo "${{ secrets.PASSWORD }}" > ~/.ssh/id_rsa
                   ssh-keyscan -t rsa -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
               - name: connect and push
                 run: ssh ${{ secrets.PASSWORD }}@${{ secrets.HOST }}
               - name: clean
                 run: rm -rf ~/.ssh


               
              
              

             
                           
           
           
         
            
     
    
 
           
              

            

        
