 name: voting_app

 on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main
    workflow_dispatch:

 jobs:
    build:
      runs-on: ubuntu-24.04
      steps: 
        - uses: actions/checkout@v2
        - name: first-bash
          run: bash ./test.sh

        - name : Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.10'

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip  # update pip 
            pip install -r requirements.txt   # Install dependencies belong  requirements.txt
        - name: create repo and downloads files in this repo
          run: |
             mkdir voting_app_repo
             cp -r repo_voting voting_app_repo
             ls -al voting_app_repo/repo_voting
        - name: give all ip addrese
          run: |
             ip a
            
             
        - name: Upload files as artifact
          uses: actions/upload-artifact@v3
          with:
           name: shared-files
           path: voting_app_repo
      
  
     
    
 
           
              

            

        
